In [ ]:
{'Guayaquil': {'robo vehiculo':605, 'asalto':6345,...},
'Cuenca': {'robo vehiculo':123, 'asalto':676,...},
}

In [14]:
def cargaDatos(): 
    dicc = {'Guayaquil': {'robo vehiculo':605, 'asalto':6345},
'Cuenca': {'robo vehiculo':123, 'asalto':676},'Quito': {'robo vehiculo':2, 'asalto':500}}
    return dicc
#[[GUAYAQUIL, CUENCA],[ROBO VEHICULO, ASALTO]]
#EN DICCIONARIOS LA CLAVE NO SE REPITE 


In [15]:
diccionario= cargaDatos()
print(diccionario)

{'Guayaquil': {'robo vehiculo': 605, 'asalto': 6345}, 'Cuenca': {'robo vehiculo': 123, 'asalto': 676}, 'Quito': {'robo vehiculo': 2, 'asalto': 500}}


In [5]:
list(diccionario.keys())

['Guayaquil', 'Cuenca']

In [9]:
delitos=[]
for valores in diccionario.values():
    for delito, valor in valores.items():
        if delito not in delitos:
            delitos.append(delito)
        

('robo vehiculo', 605)
('asalto', 6345)
('robo vehiculo', 123)
('asalto', 676)


In [16]:
def ciudadesCrimenes(diccionario):  
    ciudadesUnicas= list(diccionario.keys())
    delitos=[]
    for valores in diccionario.values():
        for delito, valor in valores.items():
            if delito not in delitos:
                delitos.append(delito)
            
    return ciudadesUnicas, delitos

In [17]:
ciudades, delitos = ciudadesCrimenes(diccionario)
print(ciudades)

['Guayaquil', 'Cuenca', 'Quito']


In [18]:
print(delitos)

['robo vehiculo', 'asalto']


In [21]:
import numpy as np
cantidadCiudades= len(ciudades)
cantidadDelitos= len(delitos)

matrizCrimenes= np.zeros((cantidadCiudades,cantidadDelitos), dtype=int)

print(matrizCrimenes)


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [26]:
for ciudad, dicc in diccionario.items():
    for delito, cantidad in dicc.items():
        print(ciudad)
        print(delito)
        print(cantidad)
        cantidad= int(cantidad)
        indiceCiudad=  ciudades.index(ciudad)
        indiceDelito= delitos.index(delito)
        matrizCrimenes[indiceCiudad,indiceDelito]= cantidad

print(matrizCrimenes)
    

Guayaquil
robo vehiculo
605
Guayaquil
asalto
6345
Cuenca
robo vehiculo
123
Cuenca
asalto
676
Quito
robo vehiculo
2
Quito
asalto
500
[[6.050e+02 6.345e+03]
 [1.230e+02 6.760e+02]
 [2.000e+00 5.000e+02]]


In [27]:
def crearMatriz():
    ciudades, delitos = ciudadesCrimenes(diccionario)
    cantidadCiudades= len(ciudades)
    cantidadDelitos= len(delitos)

    matrizCrimenes= np.zeros((cantidadCiudades,cantidadDelitos))
    for ciudad, dicc in diccionario.items():
        for delito, cantidad in dicc.items():
            cantidad= int(cantidad)
            indiceCiudad=  ciudades.index(ciudad)
            indiceDelito= delitos.index(delito)
            matrizCrimenes[indiceCiudad,indiceDelito]= cantidad

    return matrizCrimenes



In [28]:
matrizCrimenes= crearMatriz()

In [44]:
cantidadCrimenesCiudad= np.sum(matrizCrimenes,axis=1)# incidentes por ciudades
poblacion = np.array([1000,800,100])
indicePerCapita= cantidadCrimenesCiudad/poblacion #formula del ejercicio
indiceSort = np.argsort(indicePerCapita) # me los indices de como deberian estar ordenados
vectorCiudades= np.array(ciudades) #convierte la lista en un vector 
ciudadesOrdenadas= vectorCiudades[indiceSort] #me ordena la lista de menor a valor segun indiceSort
mayoresCiudadesOrdenadas= ciudadesOrdenadas[::-1] #de mayor a menor
print(mayoresCiudadesOrdenadas)
print(mayoresCiudadesOrdenadas[:2]) #solo obtiene el top2, top3, topn

[6950.  799.  502.]
[6.95    0.99875 5.02   ]
['Guayaquil' 'Quito' 'Cuenca']
['Guayaquil' 'Quito']


In [ ]:
def ciudadesMenosSeguras(matriz, ciudades, delitos, tipoDelito, poblacion):